services:
  - type: web
    name: chapchap-server
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        sync: false
      - key: SESSION_SECRET
        sync: false
    autoDeploy: true 